### ISSUE TITLE
不支持 python3?

### ISSUE THREAD

**Issue by lidaobing** [jdcloud-cmw/jdsf-demo-python#1]
```
$ pwd
/Users/lidaobing/workspace/jdcloud/jdsf-demo-python/demo_client
$ python3 app.py
Traceback (most recent call last):
  File "app.py", line 8, in <module>
    from loadbalance.lbrequest import LoadBalanceSession
  File "/Users/lidaobing/workspace/jdcloud/jdsf-demo-python/demo_client/loadbalance/lbrequest.py", line 1, in <module>
    from urlparse import urlparse
ModuleNotFoundError: No module named 'urlparse'
```

**Comment by shijunLee** [comment]
python3 没有测试过，稍后 测试完善一下

**Comment by shijunLee** [comment]
已经添加了 python3 的支持
